### ISSUE TITLE
Error trying to use versions 3.4.23 / 3.4.22 / 3.4.21

### ISSUE THREAD

**Issue by mel-rocher** [Daniel-KM/Omeka-S-module-BulkExport#12]
Error trying to use versions 3.4.23 / 3.4.22 / 3.4.21 : 
" Fatal error: Declaration of BulkExport\Traits\OpenDocumentTextTemplateTrait::writeFields(array $fields): BulkExport\Traits\OpenDocumentTextTemplateTrait must be compatible with BulkExport\Writer\AbstractFieldsWriter::writeFields(array $fields): BulkExport\Writer\AbstractFieldsWriter in /home/ahp/sites/iip/modules/BulkExport/src/Writer/OpenDocumentTextWriter.php on line 74 "

Tried installation for versions above from master
Version 3.4.20 works

**Comment by Daniel-KM** [comment]
Can you upgrade to 3.4.28 or more? And check if composer is updated if you use the git version.
