### ISSUE TITLE
Error plugin omeka-s 4.0.4

### ISSUE THREAD

**Issue by AngeloVenera** [Daniel-KM/Omeka-S-module-BulkExport#13]
Hi Daniel,

when i try to use the plugin i have this error:

Laminas\Permissions\Acl\Exception\InvalidArgumentException: Resource 'BulkImport\Api\Adapter\ImporterAdapter' not found in /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-permissions-acl/src/Acl.php:286
Stack trace:
#0 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-permissions-acl/src/Acl.php(732): Laminas\Permissions\Acl\Acl->getResource()
#1 /srv/http/omeka-s-4.0.4/application/src/Permissions/Acl.php(87): Laminas\Permissions\Acl\Acl->isAllowed()
#2 /srv/http/omeka-s-4.0.4/application/src/View/Helper/UserIsAllowed.php(36): Omeka\Permissions\Acl->userIsAllowed()
#3 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(407): Omeka\View\Helper\UserIsAllowed->__invoke()
#4 /srv/http/omeka-s-4.0.4/modules/BulkExport/view/bulk/admin/bulk-export/index.phtml(21): Laminas\View\Renderer\PhpRenderer->__call()
#5 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('...')
#6 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render()
#7 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render()
#8 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren()
#9 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render()
#10 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render()
#11 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners()
#12 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent()
#13 /srv/http/omeka-s-4.0.4/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest()
#14 /srv/http/omeka-s-4.0.4/index.php(21): Laminas\Mvc\Application->run()
#15 {main}

Ciao Angelo

**Comment by Daniel-KM** [comment]
Thanks!
