### ISSUE TITLE
Fatal error: Uncaught Error (MetadataBrowse conflict?)

### ISSUE THREAD

**Issue by alfonsomontejo** [Daniel-KM/Omeka-S-module-BulkExport#2]
After processing the items, the process shows an error and freezes. The last log message shows:

`Fatal error: Uncaught Error: Call to a member function getParams() on null in /home/web/www/modules/MetadataBrowse/Module.php:158
Stack trace:
#0 /home/web/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): MetadataBrowse\Module->repValueHtml(Object(Zend\EventManager\Event))
#1 /home/web/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(144): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#2 /home/web/www/application/src/Api/Representation/ValueRepresentation.php(56): Zend\EventManager\EventManager->trigger('rep.value.html', Object(Omeka\Api\Representation\ValueRepresentation), Object(ArrayObject))
#3 /home/web/www/modules/BulkExport/src/Traits/MetadataToStringTrait.php(210): Omeka\Api\Representation\ValueRepresentation->asHtml()
#4 /home/web/www/modules/BulkExport/src/Writer/AbstractSpreadsheetWriter.php(258): BulkExport\Writer\Abstract
in /home/web/www/modules/MetadataBrowse/Module.php on line 158`

Thanks for your work.

**Comment by Daniel-KM** [comment]
Probably fixed in last version (3.0.12). Can you retry? Thanks.

**Comment by alfonsomontejo** [comment]
Installed BulkExport-3.0.12.1. Two errors and stuck in the "in progress" state:

`Omeka\Service\Exception\RuntimeException: Cannot manage settings when no target ID is set. in /home/omekasdb/www/application/src/Settings/AbstractTargetSettings.php:97
Stack trace:
#0 /home/omekasdb/www/application/src/Settings/AbstractSettings.php(149): Omeka\Settings\AbstractTargetSettings->setCache()
#1 /home/omekasdb/www/application/src/Settings/AbstractSettings.php(95): Omeka\Settings\AbstractSettings->cache()
#2 /home/omekasdb/www/application/src/Settings/AbstractTargetSettings.php(71): Omeka\Settings\AbstractSettings->get('metadata_browse...', Array)
#3 /home/omekasdb/www/modules/MetadataBrowse/Module.php(182): Omeka\Settings\AbstractTargetSettings->get('metadata_browse...', Array)
#4 /home/omekasdb/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): MetadataBrowse\Module->repValueHtml(Object(Zend\EventManager\Event))
#5 /home/omekasdb/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(144): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#6 /home/omekasdb/www/application/src/Api/Representation/ValueRepresentation.php(56): Zend\EventManager\EventManager->trigger('rep.value.html', Object(Omeka\Api\Representation\ValueRepresentation), Object(ArrayObject))
#7 /home/omekasdb/www/modules/BulkExport/src/Traits/MetadataToStringTrait.php(232): Omeka\Api\Representation\ValueRepresentation->asHtml()
#8 /home/omekasdb/www/modules/BulkExport/src/Writer/AbstractSpreadsheetWriter.php(88): BulkExport\Writer\AbstractFieldsWriter->stringMetadata(Object(Omeka\Api\Representation\ItemRepresentation), 'dcterms:bibliog...')
#9 /home/omekasdb/www/modules/BulkExport/src/Writer/AbstractFieldsWriter.php(277): BulkExport\Writer\AbstractSpreadsheetWriter->getDataResource(Object(Omeka\Api\Representation\ItemRepresentation))
#10 /home/omekasdb/www/modules/BulkExport/src/Writer/AbstractFieldsWriter.php(212): BulkExport\Writer\AbstractFieldsWriter->appendResourcesForResourceType('o:Item')
#11 /home/omekasdb/www/modules/BulkExport/src/Writer/AbstractFieldsWriter.php(147): BulkExport\Writer\AbstractFieldsWriter->appendResources()
#12 /home/omekasdb/www/modules/BulkExport/src/Job/Export.php(67): BulkExport\Writer\AbstractFieldsWriter->process()
#13 /home/omekasdb/www/application/src/Job/DispatchStrategy/Synchronous.php(34): BulkExport\Job\Export->perform()
#14 /home/omekasdb/www/modules/Log/src/Job/Dispatcher.php(32): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#15 /home/omekasdb/www/application/data/scripts/perform-job.php(43): Log\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Log\Job\DispatchStrategy\Synchronous))
#16 {main}`

`Fatal error: Uncaught ErrorException: openlog() has been disabled for security reasons in /home/omekasdb/www/vendor/zendframework/zend-log/src/Writer/Syslog.php:161
Stack trace:
#0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'openlog() has b...', '/home/patrimoni...', 161, Array)
#1 /home/omekasdb/www/vendor/zendframework/zend-log/src/Writer/Syslog.php(161): openlog('omeka-s', 1, 8)
#2 /home/omekasdb/www/vendor/zendframework/zend-log/src/Writer/Syslog.php(244): Zend\Log\Writer\Syslog->initializeSyslog()
#3 /home/omekasdb/www/vendor/zendframework/zend-log/src/Writer/AbstractWriter.php(283): Zend\Log\Writer\Syslog->doWrite(Array)
#4 /home/omekasdb/www/vendor/zendframework/zend-log/src/Logger.php(460): Zend\Log\Writer\AbstractWriter->write(Array)
#5 /home/omekasdb/www/vendor/zendframework/zend-log/src/Logger.php(503): Zend\Log\Logger->log(3, 'Omeka\\Service\\E...', Array)
#6 /home/omekasdb/www/modules/Log/s
in /home/omekasdb/www/vendor/zendframework/zend-log/src/Writer/AbstractWriter.php on line 294`

Sorry for the delay in answering, I had to move to another city.

Thank you very much.

**Comment by Daniel-KM** [comment]
There are two errors: one in logs: by default, the module Log store fatal errors in syslog, but your syslog does not allow that. You have to add this is your `config/local.config.php`:
```php
    'logger' => [
        'syslog' => false,
    ],
```
For the issue, indeed, it is related to MetadataBrowse, that tries to create a link. To fix it, you can disable MetadataBrowse temporarely, or let the option "Value format" as "String", not "html". I fixed this issue in many places, but I have to fix it somewhere else.

**Comment by alfonsomontejo** [comment]
Thank you very much Daniel for your detailed answer and help. Greetings

**Comment by Daniel-KM** [comment]
This is fixed in last version.
