### ISSUE TITLE
Value Suggest URL only

### ISSUE THREAD

**Issue by alfonsomontejo** [Daniel-KM/Omeka-S-module-BulkExport#3]
When exporting items, the fields in which the Value Suggest module is used only return the URL of the vocabulary entry. It would be important that the reports could return the term.

For example, for the term "Acuarela", Bulk Export returns "http://tesauros.mecd.es/tesauros/tecnicas/1181621" and not the term text regardless of the exporter configuration.

Thank you first of all for your work and excuse my English.

**Comment by Daniel-KM** [comment]
There is an option for that "Format uri", that can be "uri", "uri label" or "html".

**Comment by alfonsomontejo** [comment]
Thanks!
