### ISSUE TITLE
ParseError: syntax error, unexpected ')' in /var/www/html/modules/BulkExport/Module.php:66

### ISSUE THREAD

**Issue by hxsllc** [Daniel-KM/Omeka-S-module-BulkExport#5]
Error encountered upon "Install" of module, with latest release 3.3.13.1 (and also 3.3.13.0). On an AWS EC2 server running PHP 7.2.

Omeka S encountered an error

ParseError
syntax error, unexpected ')'

Details:

ParseError: syntax error, unexpected ')' in /var/www/html/modules/BulkExport/Module.php:66
Stack trace:
#0 /var/www/html/vendor/laminas/laminas-loader/src/ModuleAutoloader.php(206): Laminas\Loader\ModuleAutoloader->loadModuleFromDir('/var/www/html/m...', 'BulkExport\\Modu...')
#1 [internal function]: Laminas\Loader\ModuleAutoloader->autoload('BulkExport\\Modu...')
#2 /var/www/html/application/src/Module/Manager.php(368): spl_autoload_call('BulkExport\\Modu...')
#3 /var/www/html/application/src/Module/Manager.php(239): Omeka\Module\Manager->getModuleObject(Object(Omeka\Module\Module))
#4 /var/www/html/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install(Object(Omeka\Module\Module))
#5 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\Admin\ModuleController->installAction()
#6 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#7 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#8 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(105): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#9 /var/www/html/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#10 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#12 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#13 /var/www/html/index.php(21): Laminas\Mvc\Application->run()
#14 {main}

**Comment by Daniel-KM** [comment]
Fixed for php < 8.
